/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as AuthedDashboardProfileRouteImport } from './routes/_authed/dashboard/profile'
import { Route as AuthedDashboardNotificationsRouteImport } from './routes/_authed/dashboard/notifications'
import { Route as AuthedDashboardListingsIndexRouteImport } from './routes/_authed/dashboard/listings/index'
import { Route as AuthedDashboardEventsIndexRouteImport } from './routes/_authed/dashboard/events/index'
import { Route as AuthedDashboardCollectionIndexRouteImport } from './routes/_authed/dashboard/collection/index'
import { Route as AuthedDashboardListingsNewRouteImport } from './routes/_authed/dashboard/listings/new'
import { Route as AuthedDashboardListingsListingIdRouteImport } from './routes/_authed/dashboard/listings/$listingId'
import { Route as AuthedDashboardEventsNewRouteImport } from './routes/_authed/dashboard/events/new'
import { Route as AuthedDashboardCollectionImportRouteImport } from './routes/_authed/dashboard/collection/import'
import { Route as AuthedDashboardCollectionAddRouteImport } from './routes/_authed/dashboard/collection/add'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDashboardRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardProfileRoute = AuthedDashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedDashboardRoute,
} as any)
const AuthedDashboardNotificationsRoute =
  AuthedDashboardNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardListingsIndexRoute =
  AuthedDashboardListingsIndexRouteImport.update({
    id: '/listings/',
    path: '/listings/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardEventsIndexRoute =
  AuthedDashboardEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardCollectionIndexRoute =
  AuthedDashboardCollectionIndexRouteImport.update({
    id: '/collection/',
    path: '/collection/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardListingsNewRoute =
  AuthedDashboardListingsNewRouteImport.update({
    id: '/listings/new',
    path: '/listings/new',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardListingsListingIdRoute =
  AuthedDashboardListingsListingIdRouteImport.update({
    id: '/listings/$listingId',
    path: '/listings/$listingId',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardEventsNewRoute =
  AuthedDashboardEventsNewRouteImport.update({
    id: '/events/new',
    path: '/events/new',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardCollectionImportRoute =
  AuthedDashboardCollectionImportRouteImport.update({
    id: '/collection/import',
    path: '/collection/import',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardCollectionAddRoute =
  AuthedDashboardCollectionAddRouteImport.update({
    id: '/collection/add',
    path: '/collection/add',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/notifications': typeof AuthedDashboardNotificationsRoute
  '/dashboard/profile': typeof AuthedDashboardProfileRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dashboard/': typeof AuthedDashboardIndexRoute
  '/dashboard/collection/add': typeof AuthedDashboardCollectionAddRoute
  '/dashboard/collection/import': typeof AuthedDashboardCollectionImportRoute
  '/dashboard/events/new': typeof AuthedDashboardEventsNewRoute
  '/dashboard/listings/$listingId': typeof AuthedDashboardListingsListingIdRoute
  '/dashboard/listings/new': typeof AuthedDashboardListingsNewRoute
  '/dashboard/collection/': typeof AuthedDashboardCollectionIndexRoute
  '/dashboard/events/': typeof AuthedDashboardEventsIndexRoute
  '/dashboard/listings/': typeof AuthedDashboardListingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/notifications': typeof AuthedDashboardNotificationsRoute
  '/dashboard/profile': typeof AuthedDashboardProfileRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/dashboard/collection/add': typeof AuthedDashboardCollectionAddRoute
  '/dashboard/collection/import': typeof AuthedDashboardCollectionImportRoute
  '/dashboard/events/new': typeof AuthedDashboardEventsNewRoute
  '/dashboard/listings/$listingId': typeof AuthedDashboardListingsListingIdRoute
  '/dashboard/listings/new': typeof AuthedDashboardListingsNewRoute
  '/dashboard/collection': typeof AuthedDashboardCollectionIndexRoute
  '/dashboard/events': typeof AuthedDashboardEventsIndexRoute
  '/dashboard/listings': typeof AuthedDashboardListingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/_authed/dashboard/notifications': typeof AuthedDashboardNotificationsRoute
  '/_authed/dashboard/profile': typeof AuthedDashboardProfileRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/_authed/dashboard/collection/add': typeof AuthedDashboardCollectionAddRoute
  '/_authed/dashboard/collection/import': typeof AuthedDashboardCollectionImportRoute
  '/_authed/dashboard/events/new': typeof AuthedDashboardEventsNewRoute
  '/_authed/dashboard/listings/$listingId': typeof AuthedDashboardListingsListingIdRoute
  '/_authed/dashboard/listings/new': typeof AuthedDashboardListingsNewRoute
  '/_authed/dashboard/collection/': typeof AuthedDashboardCollectionIndexRoute
  '/_authed/dashboard/events/': typeof AuthedDashboardEventsIndexRoute
  '/_authed/dashboard/listings/': typeof AuthedDashboardListingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/api/rpc/$'
    | '/dashboard/'
    | '/dashboard/collection/add'
    | '/dashboard/collection/import'
    | '/dashboard/events/new'
    | '/dashboard/listings/$listingId'
    | '/dashboard/listings/new'
    | '/dashboard/collection/'
    | '/dashboard/events/'
    | '/dashboard/listings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/api/rpc/$'
    | '/dashboard'
    | '/dashboard/collection/add'
    | '/dashboard/collection/import'
    | '/dashboard/events/new'
    | '/dashboard/listings/$listingId'
    | '/dashboard/listings/new'
    | '/dashboard/collection'
    | '/dashboard/events'
    | '/dashboard/listings'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/dashboard'
    | '/auth/login'
    | '/_authed/dashboard/notifications'
    | '/_authed/dashboard/profile'
    | '/api/rpc/$'
    | '/_authed/dashboard/'
    | '/_authed/dashboard/collection/add'
    | '/_authed/dashboard/collection/import'
    | '/_authed/dashboard/events/new'
    | '/_authed/dashboard/listings/$listingId'
    | '/_authed/dashboard/listings/new'
    | '/_authed/dashboard/collection/'
    | '/_authed/dashboard/events/'
    | '/_authed/dashboard/listings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard/profile': {
      id: '/_authed/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthedDashboardProfileRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/notifications': {
      id: '/_authed/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof AuthedDashboardNotificationsRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/listings/': {
      id: '/_authed/dashboard/listings/'
      path: '/listings'
      fullPath: '/dashboard/listings/'
      preLoaderRoute: typeof AuthedDashboardListingsIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/events/': {
      id: '/_authed/dashboard/events/'
      path: '/events'
      fullPath: '/dashboard/events/'
      preLoaderRoute: typeof AuthedDashboardEventsIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/collection/': {
      id: '/_authed/dashboard/collection/'
      path: '/collection'
      fullPath: '/dashboard/collection/'
      preLoaderRoute: typeof AuthedDashboardCollectionIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/listings/new': {
      id: '/_authed/dashboard/listings/new'
      path: '/listings/new'
      fullPath: '/dashboard/listings/new'
      preLoaderRoute: typeof AuthedDashboardListingsNewRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/listings/$listingId': {
      id: '/_authed/dashboard/listings/$listingId'
      path: '/listings/$listingId'
      fullPath: '/dashboard/listings/$listingId'
      preLoaderRoute: typeof AuthedDashboardListingsListingIdRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/events/new': {
      id: '/_authed/dashboard/events/new'
      path: '/events/new'
      fullPath: '/dashboard/events/new'
      preLoaderRoute: typeof AuthedDashboardEventsNewRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/collection/import': {
      id: '/_authed/dashboard/collection/import'
      path: '/collection/import'
      fullPath: '/dashboard/collection/import'
      preLoaderRoute: typeof AuthedDashboardCollectionImportRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/collection/add': {
      id: '/_authed/dashboard/collection/add'
      path: '/collection/add'
      fullPath: '/dashboard/collection/add'
      preLoaderRoute: typeof AuthedDashboardCollectionAddRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
  }
}

interface AuthedDashboardRouteChildren {
  AuthedDashboardNotificationsRoute: typeof AuthedDashboardNotificationsRoute
  AuthedDashboardProfileRoute: typeof AuthedDashboardProfileRoute
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
  AuthedDashboardCollectionAddRoute: typeof AuthedDashboardCollectionAddRoute
  AuthedDashboardCollectionImportRoute: typeof AuthedDashboardCollectionImportRoute
  AuthedDashboardEventsNewRoute: typeof AuthedDashboardEventsNewRoute
  AuthedDashboardListingsListingIdRoute: typeof AuthedDashboardListingsListingIdRoute
  AuthedDashboardListingsNewRoute: typeof AuthedDashboardListingsNewRoute
  AuthedDashboardCollectionIndexRoute: typeof AuthedDashboardCollectionIndexRoute
  AuthedDashboardEventsIndexRoute: typeof AuthedDashboardEventsIndexRoute
  AuthedDashboardListingsIndexRoute: typeof AuthedDashboardListingsIndexRoute
}

const AuthedDashboardRouteChildren: AuthedDashboardRouteChildren = {
  AuthedDashboardNotificationsRoute: AuthedDashboardNotificationsRoute,
  AuthedDashboardProfileRoute: AuthedDashboardProfileRoute,
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
  AuthedDashboardCollectionAddRoute: AuthedDashboardCollectionAddRoute,
  AuthedDashboardCollectionImportRoute: AuthedDashboardCollectionImportRoute,
  AuthedDashboardEventsNewRoute: AuthedDashboardEventsNewRoute,
  AuthedDashboardListingsListingIdRoute: AuthedDashboardListingsListingIdRoute,
  AuthedDashboardListingsNewRoute: AuthedDashboardListingsNewRoute,
  AuthedDashboardCollectionIndexRoute: AuthedDashboardCollectionIndexRoute,
  AuthedDashboardEventsIndexRoute: AuthedDashboardEventsIndexRoute,
  AuthedDashboardListingsIndexRoute: AuthedDashboardListingsIndexRoute,
}

const AuthedDashboardRouteWithChildren = AuthedDashboardRoute._addFileChildren(
  AuthedDashboardRouteChildren,
)

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
